# FROM https://github.com/osmoscraft/osmosfeed-demo/blob/main/.github/workflows/update-feed.yaml
# changed from node-version: "16" to node-version: "20"
name: Build site on scheulde or main branch update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm i
      - name: Build examples
        run: npm run build
      - name: Copy output
        run: npm run copy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
